extends Node

const MAX_REFLECTIONS = 10

const POSITION_TOLERANCE = 7

const MOVE_SPEED = 110
const HEAVY_MOVE_SPEED = 60

const FALL_SPEED = 250

const JUMP_SPEED = 50
const HEAVY_JUMP_SPEED = 40

const ACCELERATION = 0.2
const AIR_ACCELERATION = 0.1
const HEAVY_ACCELERATION = 0.1
const AIR_HEAVY_ACCELERATION = 0.05

const GRAVITY = 0.09
const HELD_GRAVITY = 0.035

const ACTION_RAYCAST_LENGHT = 16

const COYOTE_TIME = 0.07
const LOG_JUMP_TIME = 0.07
